"use client";

import { FormEvent, useEffect, useState } from "react";

type Preferences = { targetRoles: string[]; locations: string[]; employmentTypes: string[]; remotePreference: "REMOTE_ONLY" | "REMOTE_OR_HYBRID" | "ANY"; minSalary: number | null; maxSalary: number | null; mode: "REVIEW" | "HYBRID" | "AUTO"; minimumScore: number; autoApplyThreshold: number; maxApplicationsPerRun: number; maxApplicationsPerDay: number; automationEnabled: boolean; autoApplyEnabled: boolean };
const initial: Preferences = { targetRoles: [], locations: [], employmentTypes: ["FULL_TIME"], remotePreference: "REMOTE_OR_HYBRID", minSalary: null, maxSalary: null, mode: "REVIEW", minimumScore: 70, autoApplyThreshold: 85, maxApplicationsPerRun: 20, maxApplicationsPerDay: 50, automationEnabled: false, autoApplyEnabled: false };

export function PreferencesEditor() {
  const [preferences, setPreferences] = useState(initial);
  const [message, setMessage] = useState("Loading preferences...");
  useEffect(() => { fetch("/api/me").then(response => response.ok ? response.json() : Promise.reject()).then(data => { setPreferences(data.preferences ?? initial); setMessage(""); }).catch(() => setMessage("Sign in to manage preferences.")); }, []);
  const set = <K extends keyof Preferences>(key: K, value: Preferences[K]) => setPreferences(current => ({ ...current, [key]: value }));
  const list = (value: string) => value.split(",").map(item => item.trim()).filter(Boolean);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { const response = await fetch("/api/preferences", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(preferences) }); const result = await response.json(); setMessage(response.ok ? "Preferences saved." : result.error || "Could not save preferences."); } catch { setMessage("Could not reach the server. Please try again."); } }
  return <form className="card editor" onSubmit={save}><label>Target roles<input value={preferences.targetRoles.join(", ")} onChange={event => set("targetRoles", list(event.target.value))} /></label><label>Locations<input value={preferences.locations.join(", ")} onChange={event => set("locations", list(event.target.value))} /></label><label>Remote preference<select value={preferences.remotePreference} onChange={event => set("remotePreference", event.target.value as Preferences["remotePreference"])}><option value="REMOTE_ONLY">Remote only</option><option value="REMOTE_OR_HYBRID">Remote or hybrid</option><option value="ANY">Any workplace</option></select></label><label>Review mode<select value={preferences.mode} onChange={event => set("mode", event.target.value as Preferences["mode"])}><option value="REVIEW">Review every application</option><option value="HYBRID">Prepare for review</option><option value="AUTO">Automatic preparation</option></select></label><label>Minimum salary<input type="number" value={preferences.minSalary ?? ""} onChange={event => set("minSalary", event.target.value ? Number(event.target.value) : null)} /></label><label>Minimum match score<input type="number" min="0" max="100" value={preferences.minimumScore} onChange={event => set("minimumScore", Number(event.target.value))} /></label><label>Daily review limit<input type="number" min="1" max="500" value={preferences.maxApplicationsPerDay} onChange={event => set("maxApplicationsPerDay", Number(event.target.value))} /></label><label className="inline-field"><input type="checkbox" checked={preferences.automationEnabled} onChange={event => set("automationEnabled", event.target.checked)} /> Enable application preparation queue</label><div className="notice info field-full"><div><strong>Automatic submission is unavailable</strong>Job-source connectors and tested employer-site adapters are not connected. Applications will remain under your review.</div></div><p className="editor-status field-full" role="status">{message}</p><div className="form-actions field-full"><span className="muted">Changes apply to your account only.</span><button className="primary">Save preferences</button></div></form>;
}