import Link from "next/link";
import { Activity, ShieldCheck } from "lucide-react";
import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function Automation() {
  const session = await getSession();
  if (!session) return <section className="card empty-state"><h2>Sign in to view automation settings</h2><Link className="button" href="/login">Sign in</Link></section>;
  const [preferences, latestRun, latestIngestion, queued] = await Promise.all([
    prisma.userPreferences.findUnique({ where: { userId: session.userId } }),
    prisma.automationRun.findFirst({ where: { userId: session.userId }, orderBy: { createdAt: "desc" } }),
    prisma.automationRun.findFirst({ where: { userId: null, status: { in: ["COMPLETED", "FAILED"] } }, orderBy: { createdAt: "desc" } }),
    prisma.application.count({ where: { userId: session.userId, status: "QUEUED" } }),
  ]);
  const ingestionResult = latestIngestion?.result && typeof latestIngestion.result === "object" ? latestIngestion.result as { source?: string; received?: number } : null;
  return <><header className="page-heading"><div><p className="eyebrow">WORKFLOW SETTINGS</p><h1>Automation</h1><p>Review discovery activity and your current controls.</p></div><Link className="button secondary" href="/preferences">Edit preferences</Link></header><section className="grid stats"><article className="card stat-card"><div className="stat-label">Application preparation</div><div className="stat" style={{fontSize:20}}>{preferences?.automationEnabled ? "Enabled" : "Paused"}</div><div className="stat-meta">applications still require your review</div></article><article className="card stat-card"><div className="stat-label">Queued for preparation</div><div className="stat">{queued}</div><div className="stat-meta">your account</div></article><article className="card stat-card"><div className="stat-label">Job discovery</div><div className="stat" style={{fontSize:17}}>{latestIngestion?.status === "COMPLETED" ? "Arbeitnow connected" : "Awaiting first sync"}</div><div className="stat-meta">scheduled daily at 06:00 UTC after Vercel deployment</div></article><article className="card stat-card"><div className="stat-label">External submission</div><div className="stat" style={{fontSize:17}}>Unavailable</div><div className="stat-meta">no ATS adapters configured</div></article></section><div className="notice"><ShieldCheck size={19}/><div><strong>Automatic submissions are not available</strong>Job listings are imported daily and matched when you browse. This system does not submit applications or operate employer sites while you are away.</div></div><section className="card automation-activity"><div className="section-heading"><h2>Latest activity</h2></div>{latestIngestion ? <div className="system-list"><div className="system-row"><span>Job import</span><span className={`badge ${latestIngestion.status === "COMPLETED" ? "" : "error"}`}>{latestIngestion.status}</span></div><div className="system-row"><span>Source</span><span>{ingestionResult?.source ?? "Arbeitnow"}</span></div><div className="system-row"><span>Imported records received</span><span>{ingestionResult?.received ?? "—"}</span></div><div className="system-row"><span>Last run</span><span>{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(latestIngestion.createdAt)} UTC</span></div></div> : <p className="muted">No scheduled import has run yet. Vercel Cron starts after the production deployment is configured.</p>}{latestRun && <div className="section-heading"><span className="muted">Latest application workflow: {latestRun.status}</span></div>}<div className="section-heading"><Link href="/applications">Review your application pipeline <span aria-hidden="true">→</span></Link></div><Activity size={0} aria-hidden="true"/></section></>;
}
